# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # This is a library, so we don't build binaries by default
    skip: true

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Bug fixes"
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999

# Since this is a library, we mainly care about source code releases
source:
  enabled: true

# Release notes
release:
  github:
    owner: naman-dave
    name: vault-watcher
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## Vault Watcher {{ .Tag }}
    
    Thank you for using vault-watcher! This release includes the following changes:
  footer: |
    ## Installation
    
    ```bash
    go get github.com/naman-dave/vault-watcher@{{ .Tag }}
    ```
    
    **Full Changelog**: https://github.com/naman-dave/vault-watcher/compare/{{ .PreviousTag }}...{{ .Tag }}

# Disable features we don't need for a library
dockers:
  - skip_push: true
    dockerfile: Dockerfile.skip

brews:
  - skip_upload: true

nfpms:
  - skip_upload: true